language: node_js

node_js:
- "12"

branches:
  only:
  - source
  - /feature\/.*/
  - /fix\/.*/
  - /test\/.*/
  - /deploy-.*/

before_install:
- npm install hexo-cli -g
- npm install

before_script:
- git config --global user.name 'comicat-hu'
- git config --global user.email 'senline39518@gmail.com'
- sed -i'' "s~https://github.com/comicat-hu/blog.git~https://${GITHUB_TOKEN}:x-oauth-basic@github.com/comicat-hu/blog.git~" _config.yml

script:
- hexo -v
- hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: source